#!/usr/bin/env bash
set -eu

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

if ! cargo fmt --check; then
	cat <<\EOF
Run `cargo fmt` before committing code.

Don't forget to add the changes after formatting
EOF
	exit 1
fi

if ! nix fmt -- --fail-on-change; then
	cat <<\EOF
Run `nix fmt` before committing code

Don't forget to add the changes after formatting
EOF
	exit 1
fi

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if test $(git diff-index --cached --name-only --diff-filter=A -z $against |
	LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
