i2c_device = "/dev/i2c-1"

[device_config.buzzer]
gpio_chip = "/dev/gpiochip0"
line = 0
internal_pull_resistor = true

[device_config.select]
gpio_chip = "/dev/gpiochip0"
line = 1
internal_pull_resistor = true

[device_config.prev]
gpio_chip = "/dev/gpiochip0"
line = 2
internal_pull_resistor = true

[device_config.next]
gpio_chip = "/dev/gpiochip0"
line = 3
internal_pull_resistor = true

[device_config.dht]
gpio_chip = "/dev/gpiochip0"
line = 4
internal_pull_resistor = true
