[package]
name = "alarm-clock"
version = "0.2.0"
authors = ["Alex Sampley"]
edition = "2021"

[features]
default = []

[dependencies]
dir-static = { path = "../dir-static" }
pre-table = { path = "../pre-table" }

embassy-executor = { version = "0.7.0", features = ["defmt", "nightly"] }
embassy-futures = { version = "0.1.1" }
embassy-sync = { version = "0.6.1", features = ["defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt", "generic-queue-8"] }

embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
embedded-hal-async = { version = "1.0", features = ["defmt-03"] }
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"

critical-section = "1.2.0"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
enum_dispatch = "0.3.13"
futures = { version = "0.3.31", default-features = false }
heapless = { version = "0.8.0", default-features = false, features = ["serde", "defmt-03"] }
libm = { version = "0.2.11" }
log = "0.4.22"
midly = { version = "0.5.3", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = "0.6.0"
sized-dst = "0.1.1"
static_cell = { version = "2.1.0", features = ["nightly"] }
thiserror = { version = "2.0.9", default-features = false }

[target.'cfg(target_arch = "xtensa")'.dependencies]
esp-backtrace = { version = "0.15.0", features = ["esp32s3", "exception-handler", "panic-handler", "defmt" ] }
esp-hal = { version = "0.23.1", features = ["esp32s3", "defmt"] }
esp-hal-embassy = { version = "0.6.0", features = ["esp32s3"] }
